name ='kinkyfans'

compatibility_date ='2024-09-23'
compatibility_flags = ['nodejs_compat']

main = '.worker-next/index.mjs'
assets = { directory = '.worker-next/assests', binding = 'ASSETS' }

pages_build_output_dir = "dist"